### PR TITLE
Added some unicorn horn textures for the pipes.

### PR DESCRIPTION
**Pull request by K1ngjulien**
The textures should line up at the top and bottom. In the paitDotNet folder there are the original files if you want to edit them.

I'll try to implement them later, maybe someone else will be faster

### CODE REVIEW

**Comment by K1ngjulien** [comment]
Maybe they are a little to wide but that should be scaleable in javascript

**Comment by shiffman** [comment]
Can you include a screenshot or link to your demo running via github pages? That would be helpful for reviewing the design changes!

**Comment by K1ngjulien** [comment]
I've just made the design and haven't implemented them into the game

**Comment by K1ngjulien** [comment]
They are not yet implemented into the game

**Comment by K1ngjulien** [comment]
Is there a reason why this image is 500:400px in the first console.log and 1:1px in the second one?

image

All I've done with the images is load them like this 

    this.bodyImg = loadImage("graphics/horn_body_filled.png");
    this.tipImg = loadImage("graphics/horn_tip_filled.png");

    console.log(this.bodyImg);
    console.log(this.bodyImg.width,this.bodyImg.height)

**Comment by K1ngjulien** [comment]
Could it be that the images are loaded asynchronously?

**Comment by DaGuT** [comment]
you need to load images in preload() {} function

**Comment by K1ngjulien** [comment]
sorry I havent worked with p5 much, i just read it in the documentation. Is it ok if I do it in setup like the background image?

**Comment by DaGuT** [comment]
first you need to load all images in preload, only this way you can be sure then we setup is being executed images are loaded. Otherwise, they 90% will not

**Comment by K1ngjulien** [comment]
ok I have it now, sorry for noobieness :D

**Comment by DaGuT** [comment]
no worries, I'm with ya :D

**Comment by K1ngjulien** [comment]
the background image is loaded in setup, should it be moved?

**Comment by DaGuT** [comment]
check the new code from original master branch. It's already in preload :)

**Comment by DaGuT** [comment]
https://github.com/CodingTrain/Flappy-Bird-Clone/pull/25
this pull request relies on your work.
Do you mind if I do some coding for ya that I already did? Or I should go back to my code, so that you can later put your new tubes there?

**Pull request merged**
