### PR TITLE
Custom pipes design

### PR DESCRIPTION
**Pull request by DaGuT**

### CODE REVIEW

**Comment by DaGuT** [comment]
Do not pull, because it conflicts with https://github.com/CodingTrain/Flappy-Bird-Clone/commit/84d6e95399cde68f491bc04307de8989426b95a2

**Comment by shiffman** [comment]
I'm happy to merge the deletion of the extra images but I'd like to accept #33 which this will conflict with I think.

**Comment by DaGuT** [comment]
https://github.com/CodingTrain/Flappy-Bird-Clone/pull/25#issuecomment-371918764

This one had nice sweety unicorn stuff :D

If you merge #33 , I'll just pull everything that was updated and just will do that cleanup without this pipe changing

**Comment by DaGuT** [comment]
@shiffman dont you want these nasty pipes instead of green ones? :)

**Pull request closed without merging**
