### PR TITLE
game 'restarts' if you hit pipe

### PR DESCRIPTION
**Pull request by DaGuT**

### CODE REVIEW

**Comment by DaGuT** [comment]
https://github.com/CodingTrain/Flappy-Bird-Clone/pull/29#issuecomment-372041780
done

**Comment by MatCorgi** [comment]
You forgot to add a pipe to the pipes array and setting `frameCount = 1` doesnt work properly.

**Comment by DaGuT** [comment]
I did that in second commit :)

**Comment by MatCorgi** [comment]
From what i can see and from testing you only cleared the pipes array but did not add a new one.
When testing i got the error `TypeError: pipes[i] is undefined` due to the pipes array being empty

**Comment by DaGuT** [comment]
I could not delete my comment, sry :D

**Comment by DaGuT** [comment]
fixed :D

**Comment by MatCorgi** [comment]
Tried it and it works!
I had also tried to make my own way of restarting the game d2d590ede8a28519cb13ee27313d53f43ef3335b

**Comment by MatCorgi** [comment]
Tried it and it works!
I also tried to make the game restart by creating a pipetimer variable
8c8066c739582b34ba6a9d24398933462977db65

**Comment by shiffman** [comment]
I'd like to let @simon-tiger have a chance to add this in #29 since it was first submitted during the live stream.

**Comment by shiffman** [comment]
Handled in #29, thank you for the contribution!

**Comment by DaGuT** [comment]
yeah, gonna fix it now...

**Pull request closed without merging**
