### PR TITLE
Background image + image bird + scores + proper spacing + image pipes

### PR DESCRIPTION
**Pull request by DaGuT**
There is a moving background now with imaged pipes and bird - TRAIN! Hell yeah! Also, it now shows scores and can be now applied to ML algorithm

### CODE REVIEW

**Comment by DaGuT** [comment]
Need to fix collision. It was once fixed, but I lost that fix :(

**Comment by DaGuT** [comment]
https://github.com/CodingTrain/Flappy-Bird-Clone/issues/4
done? :)

**Comment by shiffman** [comment]
Wonderful! I am amazed by all the pull requests! Do you think you could break each small feature into a separate pull request? I want to merge the background and train image from #14 but use the pipe images from here, and possibly the pipe spacing! I will work this out when I begin live streaming in about 10 minutes.

**Comment by DaGuT** [comment]
If you want, I can just delete that background stuff :)

**Pull request closed without merging**
