### PR TITLE
gameover now RESTARTS if you hit pipe

### PR DESCRIPTION
**Pull request by DaGuT**
https://github.com/CodingTrain/Flappy-Bird-Clone/commit/f98fd174038a696c49e0384c3ae2ba39dbcc3ede - did not copy all my the code (thx) to restart the game upon hitting the pipe
@MatCorgi I'll let you push your way to spawn new pipes which is better in my opinion.

### CODE REVIEW

**Comment by MatCorgi** [comment]
I can agree that having to restart the page when dying is really annoying

**Comment by Versatilus** [comment]
I like this, but I think Dan might want to handle this specially when he adds the Neuroevolution bits. If I had gotten to it earlier in the week I would have merged it with small changes. I'd like to apologize about that. I'll try to do better in future. Thank you for the contribution!

**Comment by DaGuT** [comment]
ooooow....

**Comment by Versatilus** [comment]
I made a mistake last night. Thank you for your patience!

**Comment by Versatilus** [comment]
I think it would be nice if the player was given a brief moment to see that the game was over. That's just my personal preference, though.

**Comment by DaGuT** [comment]
@Versatilus will be done :D

**Pull request merged**
