### PR TITLE
WIP: [EXAMPLE] Convert the project to yarn/NPM and add linting/testing

### PR DESCRIPTION
**Pull request by rhbvkleef**

### CODE REVIEW

**Comment by shiffman** [comment]
Thank you for this! I'm going to hold of on adding this later as it is not presently the focus of the tutorial. Referencing #3.

**Comment by shiffman** [comment]
I think I'm maybe not ready for webpack and bundling yet? I guess I should probably make a video tutorial about this? Adding the linting is great though!

**Comment by rhbvkleef** [comment]
Let me know if you want me to restructure this and remove webpack. I'll close this since we won't merge this.

**Comment by shiffman** [comment]
Yes, I'm happy to merge a pull request that includes linting without webpack! Unit tests would also be welcome and I'd love to setup a CI for the linting and testing. (Unless all of this is a bad idea for some other reason?)

**Comment by rhbvkleef** [comment]
The current code structure is actually very bad for unit testing. A way around it would be to mock P5 functions. We'd need to restructure it quite a lot if we don't want to mock. I'll create a merge request for the rest momentarily.

**Comment by shiffman** [comment]
Great, yes, let's leave out unit testing for now.

**Pull request closed without merging**
