### PR TITLE
back to custom pipe design

### PR DESCRIPTION
**Pull request by DaGuT**
I dont get peaks back, as there is a trouble with hitbox then

### CODE REVIEW

**Comment by ZwergB** [comment]
tbh, it looks pretty strange with cut horns, but I guess it will do the trick.

For reference how it looks:
newpipes

**Comment by DaGuT** [comment]
At least it's made by user here, so no everything is fine with licence :)

**Comment by DaGuT** [comment]
@shiffman pls, merge my requests so that I can move on adding more cool stuff xD

**Comment by shiffman** [comment]
I really like the new marshmallow designs in #43 so I'm hoping we can resolve the collisions via #46. Thank you for all of your help! I'll revisit / re-open this later if need be!

**Pull request closed without merging**
