### PR TITLE
Train and Background V3.0

### PR DESCRIPTION
**Pull request by KeeghanM**
Third time lucky.. At the request of Daniel I have re-submitted the train and background.

### CODE REVIEW

**Comment by DaGuT** [comment]
You need to fix collision for your train :)

**Comment by KeeghanM** [comment]
@DaGuT yes, but Daniel wanted to keep it simple for his AI Videos, not major code overhauls.
I decided to do pure graphics changes not logic changes. Maybe I can add collision at another time, but for now I think this is suitable.

**Comment by DaGuT** [comment]
yeah, but it's possible to fix with just 2 lines of editing. Check mine master version

**Comment by KeeghanM** [comment]
It's okay @DaGuT I know how, but I went with a straight swap with Daniels original code by design. Like I said, I can add collision as a seperate pull request later.

**Comment by AmoghThungathurti** [comment]
:octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat:

**Comment by dmoor5** [comment]
suck on my toes

**Comment by shiffman** [comment]
Thank you so much! I am going to merge this! However, I am going to demonstrate merging from the command for fun. So stay tuned!

**Pull request merged**
