### PR TITLE
Score as a sprite

### PR DESCRIPTION
**Pull request by MatCorgi**
How it looks:
image
Textures are from original Flappy Bird game
Where i got it from: https://imgur.com/gallery/UuHcZ
No idea if it has any copyright issues :(

### CODE REVIEW

**Comment by DaGuT** [comment]
16??? There should be some adjustment in difficulty :D

**Comment by DaGuT** [comment]
delete old score, plz :D
just keep record

btw, sweet look. I like it

**Comment by shiffman** [comment]
Anyone know about the copyright / licensing status of original flappy bird designs?  I would like to be thoughtful and ethical about what I use in videos on YouTube. I'll have to hold off on merging until I know more. Same issue with #33 and the pipe designs.

**Comment by Versatilus** [comment]
I couldn't find a satisfying answer for this question. I found no reference to the copyright being released, nor to any sort of license. On the other hand, there was a lot of talk at the time this game was released of most of its assets being a bit too "inspired by" other properties. With that in mind, I personally would climb right up on my moral high horse and use it anyway.

I'm going to recommend **against** using it just because it looks like a whole can of worms. I don't think it would end up in any sort of legal trouble, but the principle is important.

It's really too bad. It looks like @MatCorgi put a good amount of work into this.

**Pull request closed without merging**
