### PR TITLE
 wider tubes + proper tube look (merge #23 before, pls)

### PR DESCRIPTION
**Pull request by DaGuT**
merge this https://github.com/CodingTrain/Flappy-Bird-Clone/pull/23 first, as mine relies on that request

### CODE REVIEW

**Comment by DaGuT** [comment]
now I added https://github.com/CodingTrain/Flappy-Bird-Clone/pull/25 these images so that you can use them in your video in 2h, when I'll be sleeping

**Comment by DaGuT** [comment]
added collision fix

**Comment by meiamsome** [comment]
Please don't include parallax in this PR - it is something that does not belong with these other changes and is going to be an issue with conflicts. PRs are usually preferred to be minimal changes (Pipe changes should be able to be the sprites and the width changes, I suppose).

Can you explain why your comment says the collision model fails? As far as I can tell it shouldn't

**Comment by meiamsome** [comment]
Also, I would check with @K1ngjulien whether they are OK with you using their sprites for your implementation.

**Comment by DaGuT** [comment]
Previous collision was checking if ends of image were on opposite sites of tube, not when size of bird is less than tube, it cannot be true. So now it's working. I'm playing it right now. 

Gonna delete parallax, pls merge xD So that I can go sleeping

**Comment by meiamsome** [comment]
Oh right, I saw that problem while I was on your branch and didn't realise I had already pulled it into master!

**Comment by DaGuT** [comment]
Yeah, sry for that :)

**Comment by DaGuT** [comment]
If you merge this https://github.com/CodingTrain/Flappy-Bird-Clone/pull/23 , mine code is gonna work and his commit will be seen.

Or should I rever back to my old pipe?

**Comment by K1ngjulien** [comment]
@meiamsome if you merge my pr #23  @DaGuT can implement my images if he wants to 😃

**Comment by DaGuT** [comment]
Thank you. Now I fully remade my code to use your images. They are no longer with my commits

**Comment by DaGuT** [comment]
Boom, and peaks are added
image
However, collision still thinks peak is rectangle.

Thx to https://github.com/CodingTrain/Flappy-Bird-Clone/pull/23 for his awesome paintings

**Comment by DaGuT** [comment]
@meiamsome All my changes are just for tubes. So It's small pull request :)

**Comment by K1ngjulien** [comment]
Awesome is a bit of an overstatement but thank you 😄

**Pull request merged**
